name: Build FastAPI Lambda Layer (Python 3.10)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build FastAPI Lambda Layer
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            -v "$PWD":/var/task \
            public.ecr.aws/lambda/python:3.10 \
            -c "
              set -e

              echo '== install zip =='
              yum install -y zip

              echo '== prepare layer dir =='
              rm -rf python fastapi_layer.zip
              mkdir -p python

              echo '== install dependencies =='
              pip install fastapi mangum -t python

              echo '== verify native module =='
              ls -lah python/pydantic_core

              echo '== zip layer =='
              zip -r fastapi_layer.zip python
            "

      - name: Upload layer artifact
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-layer-python310
          path: fastapi_layer.zip
