name: Build FastAPI for Lambda

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Lambda package
        run: |
          docker run --rm \
            -v "$PWD":/var/task \
            public.ecr.aws/lambda/python:3.10 \
            pip install -r requirements.txt -t .

      - name: Zip artifact
        run: |
          zip -r fastapi_lambda.zip . \
            -x "*.git*" \
            -x ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-lambda
          path: fastapi_lambda.zip
